environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - node --version
  - npm --version

build_script:


test_script:
  - npm run eslint
  - npm run test